Feature/PPTP-993
hmrc/plastic-packaging-tax-registration-frontend pull request #106
Opened 2021-07-21 16:20 UTC by RyanKellyHMRC

2021-07-22 18:08 UTC, tmc-ee requested changes
I'm aware https://github.com/hmrc/plastic-packaging-tax-registration-frontend/pull/105 isn't merged yet, but, should we address [this comment](https://github.com/hmrc/plastic-packaging-tax-registration-frontend/pull/105#discussion_r673953808) as part of this PR or the original?

2021-07-23 06:47 UTC, RyanKellyHMRC commented on test/spec/PptTestData.scala
> +import uk.gov.hmrc.plasticpackagingtax.registration.forms.{OrgType}
Imports are generally done semi-automatically by IntelliJ. I hadn't even noticed this.

2021-07-23 13:57 UTC, PauloPortugal commented on app/uk/gov/hmrc/plasticpackagingtax/registration/connectors/GrsIntegration.scala
> +  // TODO: consider implementing these methods here as they are very similar for all business entity types
:+1:

2021-07-23 14:05 UTC, PauloPortugal commented on conf/application.conf
> +
You will need some additional QA/Staging/Base config

2021-07-23 14:05 UTC, PauloPortugal approved these changes
LGTM

2021-07-26 09:30 UTC, tmc-ee approved these changes

2021-07-26 14:47 UTC, kiranprakashdigital approved these changes

2021-07-26 14:49 UTC, merged