PPTP-1787 Check your answers- Deregistration page
hmrc/plastic-packaging-tax-registration-frontend pull request #455
Opened 2022-03-29 17:24 UTC by kiranprakashdigital

### Description of Work carried through

Brief description of what/why/how.

#### Check list 
 - [x] `./precheck` was executed (Integration/Component/Unit tests)
 - [x] `sbt scalafmt test:scalafmt` was executed
 - [x] User Acceptance Tests (UAT) were run locally and have passed.
 - [x] No Accessibility errors/warnings reported by Wave
![Screenshot_20220329_182358](https://user-images.githubusercontent.com/74252533/160669802-8c9e1d6b-adce-43ef-a2a6-5ccda29f8aaf.png)

2022-03-29 19:21 UTC, tonymccrae-ee approved these changes

2022-03-30 08:18 UTC, RyanKellyHMRC requested changes
Looks good; just a couple of minor suggestions.

2022-03-30 08:18 UTC, RyanKellyHMRC commented on app/uk/gov/hmrc/plasticpackagingtax/registration/connectors/DeregistrationConnector.scala
> +    httpClient.PUT[Option[DeregistrationReason], HttpResponse](
Feels a little weird for a connector to expose an `HttpResponse`. As far as I can tell this isn't actually used (except in the tests); can we just return `Future[Either[ServiceError, Unit]]`?

2022-03-30 08:18 UTC, RyanKellyHMRC commented on app/uk/gov/hmrc/plasticpackagingtax/registration/controllers/deregistration/DeregisterCheckYourAnswersController.scala
> +              Future(Redirect(routes.DeregistrationSubmittedController.displayPage()))
Should this be `Future.successful(...)` if we want to immediately return a successful future. Doesn't `Future(...)` actually schedule running (of ...) in another thread?

2022-03-30 08:18 UTC, RyanKellyHMRC commented on test/uk/gov/hmrc/plasticpackagingtax/registration/connectors/DeregistrationConnectorISpec.scala
> +        res.right.get.status mustBe OK
I think we should just be checking that a `Right` is returned here.

2022-03-30 10:34 UTC, merged